title: Jason Rivers # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Working on a little bit of everything to find the best technologies for amplifying the creativity of those around me. 
  <br><br>
  Do you have a product vision? Just wait until you're looking back at how easy we made it, wondering why you didn't start sooner.
  <br><br>
  Personally though, I love to play the guitar, make new things, and maybe take a telescope out now and again.
  <br><br>
  Connect with me on LinkedIn, always happy to answer questions or talk ideas!
  <br><br> 
  <a href="https://www.linkedin.com/in/jason-rivers-933a30109/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
